### ISSUE TITLE
SonarCloud

### ISSUE THREAD

**Issue by mmonteiroc** [softflow24/data-river#67]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Need to put in place SonarCloud project so that use it in our pipelines 
Free for all open-source projects as stated in **_[their site](https://www.sonarsource.com/plans-and-pricing/sonarcloud/)_**

Why is good to have sonar clod ? 

- Static analysis with up to date best-practices and vulnerabilities in our code
- Coverage report on new code to ensure all new code generate integrates tests
- Automatic PullRequest decorations to enable / block them

What is expected of this request ? 

- A project in sonar cloud is created
- The organization / projectkey variables are set as pipeline variables in this github repo

### Motivation 🔦

Ensuring quality of the code provided matches standards.
Ensuring that new code does not introduce known vulnerabilities.

**Comment by iploooox** [comment]
SONAR_TOKEN added to repo secrets.


Here is next steps from them:

.github/workflows/build.yml:
```yaml
name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```

sonar-project.properties
```yaml
sonar.projectKey=softflow24_data-river
sonar.organization=softflow24

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=data-river
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
```
